### ISSUE TITLE
Time in Seconds and Milliseconds did not change

### ISSUE THREAD

**Issue by nimboya** [voltrue2/node-datetime#1]
I am using this module in my Node project and used the:

var datetime = require('node-datetime');
var dt = datetime.create();
var cid = dt.now();

To generate time in milliseconds. I console.log the output and refresh my page the time does not change, except i stop it and run it again.

Solution pls

**Comment by voltrue2** [comment]
Hello,

Thank you for reaching out.

So let me try to get this clear.
`datetime.now()` returns time stamp in milliseconds and this returned timestamp is based on the instance of `DateTime`, which means that the returned timestamp of `datetime.now()` does not change unless you create another instance of `DateTime` object.

Let me have a look at it and I will get back to you.

**Comment by voltrue2** [comment]
@nimboya I have made a few changes. The changes **will** break backwards compatibility.
`datetime.now()` is now called `datetime.getTime()` and `datetime.now()` returns the current time in milliseconds that is calculated from the time offset given.

I believe this is what you expect.

It would be really great if you could have a look at it before I publish this new version of the package to npm.

Best Regards

**Comment by voltrue2** [comment]
@nimboya I went ahead and published the said version to npm.
The version is 1.0.0

**Comment by nimboya** [comment]
Alright thanks alot. I will check it and get back to you ASAP
