### ISSUE TITLE
wrong calculation of period 

### ISSUE THREAD

**Issue by shoorkaii** [voltrue2/node-datetime#10]
function getPeriod(d) {
	var hours = d.getHours();
	if (hours <= 12) {
		return PERIOD.AM;
	}
	return PERIOD.PM;
}``

you must change the condition

**Comment by voltrue2** [comment]
Hello

Thanks for pointing it out. If has to be

hours < 12 instead of <=

I’ll fix the bug ASAP

**Comment by voltrue2** [comment]
Fixed and push!

Cheers!
