### ISSUE TITLE
Date Formatting Issue

### ISSUE THREAD

**Issue by dssoma** [voltrue2/node-datetime#11]
I am doing the formatting with node date-time. But it is showing wrong only 12:00 pm, It's always showing 00:00 AM.
Example: 
time = dateTime.create('2018-07-19 12:54:55');
Ftime = time.format('I:M p');
It's Showing 00:54 AM

Please help me with this. It's very urgent.

Thanks

**Comment by voltrue2** [comment]
Hello

Thank you for reporting the bug. I have fixed the bug: 61f83d53789837c35e10846a469800027726899d

and the npm release would be version 2.0.9

Cheers

**Comment by dssoma** [comment]
Hi,
I am using node-datetime version 2.0.6
You mean I need to update the version?

**Comment by dssoma** [comment]
I have just updated the node-datetime and it's working fine.
Thank you.

**Comment by voltrue2** [comment]
Yes please
