### ISSUE TITLE
Date format issue

### ISSUE THREAD

**Issue by yoann-FM** [voltrue2/node-datetime#12]
Hi,
I would like place my datetime format like that : 3rd of August 2018 09:50:34 AM (GMT time)
it's possible ?

**Comment by voltrue2** [comment]
Hello
  

  
Currently having your day formatted with ...th, ...rd is not implemented but I could add a new format to do that.   
  

  
How critical is this feature for you?
  

  
Cheers
  

  
  

  
  
>

**Comment by voltrue2** [comment]
Hello here it is: 2eaa1e4fb088e653fbb9c55da4ed7d064bf30ac8

npm version is now: `2.1.0`

**Comment by voltrue2** [comment]
So what you want to do should be accomplished by:

```javascript
var datetime = require('node-datetime');
var d = datetime.create();
var formatted = d.format('D') + ' of ' + d.format('f Y I:M:S p') + ' (GMT time)';
```

**Comment by yoann-FM** [comment]
Hi,

I created a function do make the job.
But if you can add this option or same option as
http://php.net/manual/en/function.date.php it will be great

Regards

**Comment by voltrue2** [comment]
Closing since it has been resolved but there’s been no response
