### ISSUE TITLE
defaultFormat lost in dates produced by getDatesInRange; range in reverse order

### ISSUE THREAD

**Issue by alexeykirdin** [voltrue2/node-datetime#13]
Hello.

I'm trying to use node-datetime package, and I figured out, that format property is not inherited by objects produced by datetime.getDatesInRange() method.

Example: 
const defaultFormat = 'Y-m-d';
const datetime = require('node-datetime');
datetime.setDefaultFormat( defaultFormat );
let start = '2018-09-01', finish = '2018-09-19';

// 1 - both elements has _defaultFormat property set to defaultFormat
var boundaries = [datetime.create( start, defaultFormat ), datetime.create( finish, defaultFormat )];

// 2. using getDatesInRange() - 
let  range = dstart.getDatesInRange( dfinish );

// 3. In range, all objects has null as _defaultFormat.

Is this behaviour by design?

Question 2: 
dstart.getDatesInRange( dfinish ) throws an exception if start > finish.

I need dates in reverse order for my task. Why not to allow producing of a range in that case? It seems that code in DateTime.prototype.getDatesInRange() can handle reverse direction.

WBR, Alexey

**Comment by voltrue2** [comment]
Hello,

Regarding your question 1, I believe it is a bug. I will fix this so that if you pass an instance of DateTime object with default format set, all the instances of DateTime objects created by `getDatesInRange()`, will inherit the fotmat.

As for question 2, if you need to have the array in reverse order, why not reverse the result array?

Cheers!

**Comment by voltrue2** [comment]
Hello,

Here is the commit: 20d23c29344f2b05b8c1f75650cca4713261849b

And the latest package on npm is that includes this update is `v2.1.1`.

**Comment by alexeykirdin** [comment]
Thanks a lot for the fix.

> As for question 2, if you need to have the array in reverse order, why not reverse the result array?

The code already knows about direction, but it cannot be executed because of throw operator. For me it seems strange.

**Comment by voltrue2** [comment]
Hello,

Well internally the code does not know both directions. It only knows small -> big not other way around.

Having said that though, I suppose I could make it so that it can do reverse also.
Let me have a look.

Cheers

**Comment by voltrue2** [comment]
@alexeykirdin 

Here it is: 834fae6a9bd9dcdd283904f2d031992df7db01ef

And it is published on npm also.

Cheers
