### ISSUE TITLE
How to convert to unix time to formatted date?

### ISSUE THREAD

**Issue by praveen-kanamarlapudi** [voltrue2/node-datetime#4]
Hi,

Can you please help me understand how to convert to unix timestamp to formatted date string(ex: '2015-01-01 00:00:00')?

Sorry If it's a silly question, I am new to node and JS.

**Comment by voltrue2** [comment]
Hello

Here is how it's done:

var d = nodeDateTime.create(new Date(timestamp), formatString);
var formattedString = d.format();

**Comment by praveen-kanamarlapudi** [comment]
Hey,

Thanks for the prompt response.
