### ISSUE TITLE
How to get AM or PM with current date and time

### ISSUE THREAD

**Issue by msankar1991** [voltrue2/node-datetime#5]
```
var dt = dateTime.create();
var current_date = dt.format('Y-m-d');
```

Is there any options are available to get AM or PM with it.
And also how to convert `'08:21 AM' to '08:21:00' `

**Comment by voltrue2** [comment]
Hello

Thank you for reaching out.
Right now you can only get either 24 hours or not with "H" being the 24 hours format and "I" being the regular hours.
I will get another format to get am or pm.

Cheers

**Comment by voltrue2** [comment]
Hello,

I just published the updated version of the module.
With this version you can do something like this:

```
const datetime = require('node-datetime');
var now = datetime.create();
var formatted = now.format('Y-m-d I:M:S p');
// formatted will look something like this: 2017-09-05 02:35:20 PM
```
