### ISSUE TITLE
February is spelt Feburary when using .format('f')

### ISSUE THREAD

**Issue by MatthewJohnSymons** [voltrue2/node-datetime#6]
I have found an incorrect spelling of 'February' when using the format for the full month name. The module currently returns 'Feburary'.

<img width="396" alt="screen shot 2018-01-26 at 12 23 15" src="https://user-images.githubusercontent.com/30142703/35439694-b7816820-0293-11e8-9c36-aaaa03adef99.png">
<img width="247" alt="screen shot 2018-01-26 at 12 21 47" src="https://user-images.githubusercontent.com/30142703/35439695-b7a207a6-0293-11e8-859e-d43f849fcef6.png">

**Comment by voltrue2** [comment]
Merged and publish!

Thank you for the PR!
